# encoding=utf-8


class People:

    def __init__(self): pass

    def get_name_of_politician(self):
        return [x[0] for x in self.list_of_politicians_with_parties()]

    def get_name_of_parties(self):
        return [x[1] for x in self.list_of_politicians_with_parties()]

    def list_of_politicians_with_parties(self):

        array_of_entities = [
            (u"Milivoje Simić", u"Vanstranačka ličnost"), 
            (u"Aleksandra Radosavljević", u"Vanstranačka ličnost"), 
            (u"Siniša Mali", u"Vanstranačka ličnost"), 
            (u"Stevan Bjelić", u"Vanstranačka ličnost"), 
            (u"Veselin Milić", u"Vanstranačka ličnost"), 
            (u"Živanko Radovančev", u"Socijalistička partija Srbije"), 
            (u"Novak Nedić", u"Srpska napredna stranka"), 
            (u"Mitropolit Amfilohije Radović", u"Vanstranačka ličnost"), 
            (u"Ljiljana Smajlović", u"Vanstranačka ličnost"), 
            (u"Aleksandar Antić", u"Socijalistička partija Srbije"), 
            (u"Aleksandar Martinović", u"Srpska napredna stranka"), 
            (u"Aleksandar Marton", u"Liga socijaldemokrata Vojvodine"), 
            (u"Aleksandar Popović", u"Demokratska stranka Srbije"), 
            (u"Aleksandar Tijanić", u"Vanstranačka ličnost"), 
            (u"Aleksandar Vučić", u"Srpska napredna stranka"), 
            (u"Aleksandar Vuksanović", u"Vanstranačka ličnost"), 
            (u"Aleksandar Vulin", u"Pokret socijalista"), 
            (u"Aleksandra Jerkov", u"Demokratska stranka"), 
            (u"Andreja Mladenović", u"Samostalni DSS"), 
            (u"Balint Pastor", u"Savez vojvođanskih Mađara"), 
            (u"Bojan Kostreš", u"Liga socijaldemokrata Vojvodine"), 
            (u"Bojan Marković", u"Vanstranačka ličnost"), 
            (u"Bojan Pajtić", u"Demokratska stranka"), 
            (u"Boris Tadić", u"SocijalDemokratska stranka Srbije"), 
            (u"Borislav Pelević", u"Vanstranačka ličnost"), 
            (u"Borislav Stefanović", u"Vanstranačka ličnost"), 
            (u"Bosa Nenadić", u"Vanstranačka ličnost"), 
            (u"Boško Ničić ", u"pokret 'Živim za krajinu'"), 
            (u"Božidar Delić", u"Srpska radikalna stranka"), 
            (u"Božidar Đelić", u"Demokratska stranka"), 
            (u"Marko Karadžić", u"Liberalno demokratska partija"), 
            (u"Milovan Petrović", u"Pokret za Užice"), 
            (u"Danilo Bjelica", u"Demokratska stranka Srbije"), 
            (u"Meho Omerović", u"Socijaldemokratska partija Srbije"), 
            (u"Milan Beko", u"Vanstranačka ličnost"), 
            (u"Milutin Mrkonjić", u"Socijalistička partija Srbije"), 
            (u"Milan Draškić", u"Nova Srbija"), 
            (u"Miodrag Miljković", u"Vanstranačka ličnost"), 
            (u"Miodrag Stamenković", u"Vanstranačka ličnost"), 
            (u"Branislav Ivković", u"Srpska napredna stranka"), 
            (u"Mirjana Božidarević", u"Demokratska stranka"), 
            (u"Branislav Jovanović", u"Narodni pokret Srbije"), 
            (u"Mirjana Marković", u"Vanstranačka ličnost"), 
            (u"Milan Krkobabić", u"Partija ujedinjenih penzionera Srbije"), 
            (u"Mirko Cvetković", u"Vanstranačka ličnost"), 
            (u"Mirko Marjanović", u"Vanstranačka ličnost"), 
            (u"Milan Marković", u"Vanstranačka ličnost"), 
            (u"Dejan Jovanović", u"Vanstranačka ličnost"), 
            (u"Milan Milić", u"Vanstranačka ličnost"), 
            (u"Miroslav Petković", u"Demokratska stranka Srbije"), 
            (u"Mišo Marković", u"Demokratska stranka Srbije"), 
            (u"Milan St. Protić", u"Vanstranačka ličnost"), 
            (u"Mlađan Dinkić", u"Ujedinjeni regioni Srbije"), 
            (u"Milanko Šarančić", u"Nova Srbija"), 
            (u"Dejan Ranđić", u"Liberalno demokratska partija"), 
            (u"Momčilo Vujičić", u"Srpska radikalna stranka"), 
            (u"Momo Čolaković", u"Partija ujedinjenih penzionera Srbije"), 
            (u"Mile Ilić", u"Socijalistička partija Srbije"), 
            (u"Nada Kolundžija", u"Demokratska stranka"), 
            (u"Mileta Mihajlov", u"Demokratska stranka"), 
            (u"Nadica Momirov", u"Ujedinjeni regioni Srbije"), 
            (u"Milica Delević", u"Demokratska stranka"), 
            (u"Nata Mesarović", u"Vanstranačka ličnost"), 
            (u"Milomir Minić", u"Socijalistička partija Srbije"), 
            (u"Nataša Vučković Lesendrić", u"Vanstranačka ličnost"), 
            (u"Milorad Veljović", u"Vanstranačka ličnost"), 
            (u"Miloš Aligrudić", u"Demokratska stranka Srbije"), 
            (u"Dejan Šoškić", u"Vanstranačka ličnost"), 
            (u"Nebojša Bradić", u"Vanstranačka ličnost"), 
            (u"Nebojša Ćirić", u"Vanstranačka ličnost"), 
            (u"Miloš Bugarin", u"Vanstranačka ličnost"), 
            (u"Miloš Saramandić", u"Demokratska stranka"), 
            (u"Miloš Simonović", u"SocijalDemokratska stranka"), 
            (u"Diana Dragutinović", u"Vanstranačka ličnost"), 
            (u"Milovan Marković", u"Vanstranačka ličnost"), 
            (u"Milovan Mićović", u"Demokratska stranka"), 
            (u"Vladimir Ilić", u"Vanstranačka ličnost"), 
            (u"Dragan Drašković", u"Vanstranačka ličnost"), 
            (u"Vladimir Vukčević", u"Vanstranačka ličnost"), 
            (u"Vlajko Senić", u"Ujedinjeni regioni Srbije"), 
            (u"Vojislav Ilić", u"Nova Srbija"), 
            (u"Vojislav Koštunica", u"Vanstranačka ličnost"), 
            (u"Vojislav Šešelj", u"Srpska radikalna stranka"), 
            (u"Dragan Marković Palma", u"Jedinstvena Srbija"), 
            (u"Vuk Dinčić", u"Demokratska stranka"), 
            (u"Vuk Drašković", u"Srpski pokret obnove"), 
            (u"Vuk Jeremić", u"Vanstranačka ličnost"), 
            (u"Žarko Korać", u"Socijaldemokratska unija"), 
            (u"Dragan Pušara", u"Vanstranačka ličnost"), 
            (u"Žarko Obradović", u"Socijalistička partija Srbije"), 
            (u"Željko Ivanji", u"Srpska narodna partija"), 
            (u"Svetlana Vukajlović", u"Vanstranačka ličnost"), 
            (u"Željko Mitrović", u"Vanstranačka ličnost"), 
            (u"Željko Nikač", u"Vanstranačka ličnost"), 
            (u"Dragan Šormaz", u"Srpska napredna stranka"), 
            (u"Svetozar Čiplić", u"Demokratska stranka"), 
            (u"Željko Ožegović", u"Liberalno demokratska partija"), 
            (u"Živadin Jovanović", u"Socijalistička partija Srbije"), 
            (u"Živojin Stefanović", u"Vanstranačka ličnost"), 
            (u"Tamara Lukšić-Orlandić", u"Vanstranačka ličnost"), 
            (u"Životije Jovanović", u"Jedinstvena Srbija"), 
            (u"Zoltan Bilicki", u"Vanstranačka ličnost"), 
            (u"Tanja Miščević", u"Vanstranačka ličnost"), 
            (u"Dragutin Radosavljević", u"Vanstranačka ličnost"), 
            (u"Tigran Kiš", u"Srpska napredna stranka"), 
            (u"Tihomir Petković", u"Srpska napredna stranka"), 
            (u"Tomica Milosavljević", u"Vanstranačka ličnost"), 
            (u"Tomislav Nikolić", u"Vanstranačka ličnost"), 
            (u"Tomo Zorić", u"Vanstranačka ličnost"), 
            (u"Zoran Anđelković", u"Socijalistička partija Srbije"), 
            (u"Velimir Ilić", u"Nova Srbija"), 
            (u"Dragan Šutanovac", u"Demokratska stranka"), 
            (u"Zoran Drobnjak", u"Srpska napredna stranka"), 
            (u"Velimir Stanojević", u"Nova Srbija"), 
            (u"Zoran Martinović", u"Socijaldemokratska partija Srbije"), 
            (u"Veljko Negovanović", u"Socijalistička partija Srbije"), 
            (u"Zoran Ostojić", u"Ujedinjeni regioni Srbije"), 
            (u"Veljko Odalović", u"Socijalistička partija Srbije"), 
            (u"Zoran Rakić", u"Ujedinjeni regioni Srbije"), 
            (u"Verica Barać", u"Vanstranačka ličnost"), 
            (u"Zoran Stanković", u"Vanstranačka ličnost"), 
            (u"Dragan Todorović", u"Srpska radikalna stranka"), 
            (u"Verica Kalanović", u"Ujedinjeni regioni Srbije"), 
            (u"Zoran Đinđić", u"Demokratska stranka"), 
            (u"Zorana Marković", u"Vanstranačka ličnost"), 
            (u"Veroljub Stevanović", u"Zajedno za Šumadiju"), 
            (u"Zvonko Obradović", u"Ujedinjeni regioni Srbije"), 
            (u"Dragan Veselinov", u"Vanstranačka ličnost"), 
            (u"Vesna Martinović", u"Demokratska stranka"), 
            (u"Branka Ljiljak", u"Demokratska stranka"), 
            (u"Nebojša Pavković", u"Vanstranačka ličnost"), 
            (u"Vesna Pešić", u"Vanstranačka ličnost"), 
            (u"Dubravka Filipovski", u"Nova Srbija"), 
            (u"Nela Cvetković", u"Ujedinjeni regioni Srbije"), 
            (u"Branko Ružić", u"Socijalistička partija Srbije"), 
            (u"Gorica Dimčić-Tasić", u"Ujedinjeni regioni Srbije"), 
            (u"Nenad Čanak", u"Liga socijaldemokrata Vojvodine"), 
            (u"Dragan Vukmirović", u"Vanstranačka ličnost"), 
            (u"Bruno Vekarić", u"Vanstranačka ličnost"), 
            (u"Čedomir Čupić", u"Vanstranačka ličnost"), 
            (u"Nenad Konstantinović", u"SocijalDemokratska stranka"), 
            (u"Čedomir Jovanović", u"Liberalno demokratska partija"), 
            (u"Vladan Batić", u"Demohrišćanska stranka Srbije"), 
            (u"Igor Andonov", u"SocijalDemokratska stranka"), 
            (u"Nenad Milenković", u"Zajedno za Srbiju"), 
            (u"Čedomir Živković", u"Srpska napredna stranka"), 
            (u"Vladimir Cvijan", u"Republikanska partija"), 
            (u"Nenad Ognjenović", u"Socijalistička partija Srbije"), 
            (u"Dalibor Bubnjević", u"Vanstranačka ličnost"), 
            (u"Igor Pavličić", u"Demokratska stranka"), 
            (u"Nenad Popović", u"Srpska narodna partija"), 
            (u"Nevena Karanović", u"Ujedinjeni regioni Srbije"), 
            (u"Ištvan Pastor", u"Savez vojvođanskih Mađara"), 
            (u"Dragan Đilas", u"Demokratska stranka"), 
            (u"Nevena Petrušić", u"Vanstranačka ličnost"), 
            (u"Nikola Damnjanović", u"Demokratska stranka"), 
            (u"Ivan Andrić", u"Vanstranačka ličnost"), 
            (u"Ivan Marković", u"Vanstranačka ličnost"), 
            (u"Ivan Živadinović", u"Ujedinjeni regioni Srbije"), 
            (u"Ivana Vuletić", u"Vanstranačka ličnost"), 
            (u"Dragana Stošić", u"Socijalistička partija Srbije"), 
            (u"Ivica Dačić", u"Socijalistička partija Srbije"), 
            (u"Dragiša Simić", u"Vanstranačka ličnost"), 
            (u"Nikola Selaković", u"Srpska napredna stranka"), 
            (u"Novica Tončev", u"Socijalistička partija Srbije"), 
            (u"Oliver Dulić", u"Demokratska stranka"), 
            (u"Oliver Ivanović", u"Vanstranačka ličnost"), 
            (u"Dušan Bajatović", u"Socijalistička partija Srbije"), 
            (u"Petar Domanović", u"Srpska napredna stranka"), 
            (u"Dragiša Slijepčević", u"Vanstranačka ličnost"), 
            (u"Jasna Matić", u"Ujedinjeni regioni Srbije"), 
            (u"Jelena Trivan", u"Vanstranačka ličnost"), 
            (u"Dragoljub Janković", u"Vanstranačka ličnost"), 
            (u"Jorgovanka Tabaković", u"Srpska napredna stranka"), 
            (u"Jovan Babović", u"Socijalistička partija Srbije"), 
            (u"Jovan Krkobabić", u"Partija ujedinjenih penzionera Srbije"), 
            (u"Jovan Marković", u"Demokratska stranka"), 
            (u"Dragoljub Mićunović", u"Demokratska stranka"), 
            (u"Leposava Milićević", u"Vanstranačka ličnost"), 
            (u"Ljiljana Jovčić", u"Demokratska stranka"), 
            (u"Dušan Mihajlović", u"Vanstranačka ličnost"), 
            (u"Dragomir Marković", u"Demokratska stranka"), 
            (u"Ljubo Lazović", u"Vanstranačka ličnost"), 
            (u"Petar Škundrić", u"Socijalistička partija Srbije"), 
            (u"Maja Gojković", u"Srpska napredna stranka"), 
            (u"Predrag Petrović", u"Demokratska stranka"), 
            (u"Predrag Kon", u"Vanstranačka ličnost"), 
            (u"Slaviša Zlatanović", u"Vanstranačka ličnost"), 
            (u"Predrag Marić", u"Vanstranačka ličnost"), 
            (u"Predrag Marković", u"Ujedinjeni regioni Srbije"), 
            (u"Slobodan Homen", u"SocijalDemokratska stranka"), 
            (u"Dušan Petrović", u"Zajedno za Srbiju"), 
            (u"Slobodan Ilić", u"Demokratska stranka"), 
            (u"Radenko Luković", u"Srpska napredna stranka"), 
            (u"Radoslav Nikolić", u"Socijalistička partija Srbije"), 
            (u"Radoslav Sretenović", u"Vanstranačka ličnost"), 
            (u"Slobodan Maraš", u"Ujedinjeni regioni Srbije"), 
            (u"Radovan Draškić", u"Demokratska stranka"), 
            (u"Slobodan Milosavljević", u"Demokratska stranka"), 
            (u"Slobodan Kocić", u"Demokratska stranka"), 
            (u"Radovan Jelašić", u"Vanstranačka ličnost"), 
            (u"Dušica Davidović", u"Koalicija za Niš"), 
            (u"Rasim Ljajić", u"Socijaldemokratska partija"), 
            (u"Slobodan Milošević", u"Vanstranačka ličnost"), 
            (u"Saša Dragin", u"Demokratska stranka"), 
            (u"Slobodan Radovanović", u"Vanstranačka ličnost"), 
            (u"Saša Janković", u"Vanstranačka ličnost"), 
            (u"Slobodan Vuksanović", u"Vanstranačka ličnost"), 
            (u"Saša Pavlov", u"Srpska napredna stranka"), 
            (u"Snežana Klašnja", u"Vanstranačka ličnost"), 
            (u"Episkop Filaret Mićević", u"Vanstranačka ličnost"), 
            (u"Slavica Đukić Dejanović", u"Socijalistička partija Srbije"), 
            (u"Snežana Lakićević", u"Vanstranačka ličnost"), 
            (u"Snežana Malović", u"SocijalDemokratska stranka"), 
            (u"Filip Mitrović", u"Demokratska stranka"), 
            (u"Snežana Samardžić Marković", u"Ujedinjeni regioni Srbije"), 
            (u"Sonja Liht", u"Vanstranačka ličnost"), 
            (u"Srđan Srećković", u"Zajedno za Srbiju"), 
            (u"Gojko Veličković", u"Srpska napredna stranka"), 
            (u"Srđan Stojanović", u"Demokratska stranka"), 
            (u"Srđan Šušulić", u"Demokratska stranka"), 
            (u"Sulejman Ugljanin", u"Stranka demokratske akcije Sandžaka"), 
            (u"Goran Bogdanović", u"SocijalDemokratska stranka"), 
            (u"Suzana Grubješić", u"Ujedinjeni regioni Srbije"), 
            (u"Svetlana Jevđović Matić", u"Demokratska stranka"), 
            (u"Goran Ćirić", u"Demokratska stranka"), 
            (u"Goran Cvetanović", u"Srpska napredna stranka"), 
            (u"Goran Ješić", u"Demokratska stranka"), 
            (u"Goran Karadžić", u"Vanstranačka ličnost"), 
            (u"Goran Kaurić", u"Demokratska stranka"), 
            (u"Goran Knežević", u"Srpska napredna stranka"), 
            (u"Goran Matić", u"Vanstranačka ličnost"), 
            (u"Goran Petković", u"Ujedinjeni regioni Srbije"), 
            (u"Gorčilo Potpara", u"Vanstranačka ličnost"), 
            (u"Goran Takić", u"Vanstranačka ličnost"), 
            (u"Vladimir Terzin", u"Vanstranačka ličnost"), 
            (u"Jovica Đukić", u"Vanstranačka ličnost"), 
            (u"Aca Kovačević", u"Vanstranačka ličnost"), 
            (u"Miloje Vojinović", u"Nova Srbija"), 
            (u"Aleksandar Vesić", u"Vanstranačka ličnost"), 
            (u"Zoran Jakovljević", u"Demokratska stranka"), 
            (u"Dragan Jeremić", u"Socijalistička partija Srbije"), 
            (u"Šandor Egereši", u"Savez vojvođanskih Mađara"), 
            (u"Saša Milenić", u"Zajedno za Šumadiju"), 
            (u"Predrag Umičević", u"Demokratska stranka"), 
            (u"Miroslav Čučković", u"Srpska napredna stranka"), 
            (u"Goran Kreclović", u"Vanstranačka ličnost"), 
            (u"Zagorka Dolovac", u"Vanstranačka ličnost"), 
            (u"Zoran Blagojević", u"Vanstranačka ličnost"), 
            (u"Milena Pavlović", u"Demokratska stranka"), 
            (u"Dragana Milićević Milutinović", u"Vanstranačka ličnost"), 
            (u"Goran Radosavljević", u"SocijalDemokratska stranka"), 
            (u"Milan Popović", u"Demokratska stranka"), 
            (u"Goran Trivan", u"Socijalistička partija Srbije"), 
            (u"Ivana Avžner", u"Vanstranačka ličnost"), 
            (u"Vladica Gavrilović", u"Nova Srbija"), 
            (u"Dimitrije Lukić", u"Demokratska stranka"), 
            (u"Vladan Vasić", u"Koalicija za Pirot"), 
            (u"Ivana Dulić Marković", u"Vanstranačka ličnost"), 
            (u"Bojan Biočanin", u"Demokratska stranka Srbije"), 
            (u"Meho Mahmutović", u"Sandžačka demokratska partija"), 
            (u"Elvir Hamidović", u"Sandžačka demokratska partija"), 
            (u"Saša Vučinić", u"Demokratska stranka"), 
            (u"Blagoje Spaskovski", u"Srpska napredna stranka"), 
            (u"Marko Đurišić", u"SocijalDemokratska stranka"), 
            (u"Nebojša Zdravković", u"Grupa građana"), 
            (u"Dragan Radović", u"Zajedno za Šumadiju"), 
            (u"Nebojša Vasiljević", u"Zajedno za Šumadiju"), 
            (u"Nihad Hasanović", u"Sandžačka demokratska partija"), 
            (u"Dragan Vujadinović", u"SocijalDemokratska stranka"), 
            (u"Idriz Nuhović", u"Sandžačka demokratska partija"), 
            (u"Zorana Mihajlović", u"Srpska napredna stranka"), 
            (u"Aleksandar Jovanović ", u"Liga socijaldemokrata Vojvodine"), 
            (u"Dmitar Popović", u"Demokratska stranka"), 
            (u"Borislav Novaković", u"Demokratska stranka"), 
            (u"Vesna Arsić", u"Vanstranačka ličnost"), 
            (u"Vujica Tiosavljević", u"Nova Srbija"), 
            (u"Ljubiša Simović", u"Liberalno demokratska partija"), 
            (u"Dušan Elezović", u"Demokratska stranka"), 
            (u"Sulejman Nicević", u"Sandžačka demokratska partija"), 
            (u"Mirjana Milenković", u"Demokratska stranka"), 
            (u"Radovan Nikolić", u"Socijalistička partija Srbije"), 
            (u"Stanko Terzić", u"Socijalistička partija Srbije"), 
            (u"Dušan Mrakić", u"Socijalistička partija Srbije"), 
            (u"Branislav Nedimović", u"Srpska napredna stranka"), 
            (u"Andrej Bursać", u"Vanstranačka ličnost"), 
            (u"Nataša Cvjetković", u"Demokratska stranka"), 
            (u"Damjan Miljanić", u"Demokratska stranka Srbije"), 
            (u"Goran Vuković", u"Demokratska stranka"), 
            (u"Dragan Janjić", u"Vanstranačka ličnost"), 
            (u"Goran Jović", u"Demokratska stranka"), 
            (u"Dragan Jovanović", u"Demokratska stranka"), 
            (u"Dejan Mali", u"Demokratska stranka"), 
            (u"Željko Vidović", u"Srpski pokret obnove"), 
            (u"Tibor Fazekaš", u"Vanstranačka ličnost"), 
            (u"Bojan Đurić", u"Vanstranačka ličnost"), 
            (u"Vladimir Petrović", u"Demokratska stranka"), 
            (u"Milorad Ilić", u"Socijalistička partija Srbije"), 
            (u"Zoran Vorkapić", u"Vanstranačka ličnost"), 
            (u"Zaharije Trnavčević", u"Pokret Bogata Srbija"), 
            (u"Borko Ilić", u"Demokratska stranka Srbije"), 
            (u"Miloš Milovanović", u"Vanstranačka ličnost"), 
            (u"Milisav Petronijević", u"Socijalistička partija Srbije"), 
            (u"Siniša Bubnjević", u"Liga socijaldemokrata Vojvodine"), 
            (u"Saša Mirković", u"Vanstranačka ličnost"), 
            (u"Zenib Biberović", u"Sandžačka demokratska partija"), 
            (u"Nemanja Šarović", u"Srpska radikalna stranka"), 
            (u"Nemanja Starović", u"Srpski pokret obnove"), 
            (u"Miloš Milošević", u"Demokratska stranka"), 
            (u"Dijana Vukomanović", u"Socijalistička partija Srbije"), 
            (u"Nedeljko Šljivanac", u"Reformisti Vojvodine"), 
            (u"Milan Arsović", u"Demokratska stranka"), 
            (u"Marijan Petrović", u"Vanstranačka ličnost"), 
            (u"Andrija Penzeš", u"Demokratska stranka"), 
            (u"Nebojša Stefanović", u"Srpska napredna stranka"), 
            (u"Boško Obradović", u"Srpski pokret"), 
            (u"Živko Makarić", u"Vanstranačka ličnost"), 
            (u"Jovica Zarkula", u"Pokret Vršačka regija-Evropska regija"), 
            (u"Ivan Starčević", u"Demokratska stranka"), 
            (u"Radoslav Striković", u"Socijalistička partija Srbije"), 
            (u"Dragoslav Petrović", u"Demokratska stranka"), 
            (u"Siniša Sević", u"Vanstranačka ličnost"), 
            (u"Bratislav Petković", u"Srpska napredna stranka"), 
            (u"Milan Bačević", u"Srpska napredna stranka"), 
            (u"Alisa Marić  ", u"Vanstranačka ličnost"), 
            (u"Ivan Mrkić ", u"Vanstranačka ličnost"), 
            (u"Igor Novaković", u"Socijalistička partija Srbije"), 
            (u"Slobodan Bajić", u"Pokret Snaga Srbije"), 
            (u"Miloš Vučević", u"Srpska napredna stranka"), 
            (u"Milorad Mladenović", u"Vanstranačka ličnost"), 
            (u"Đurađ Jakšić", u"Srpska radikalna stranka"), 
            (u"Mihalj Njilaš", u"Savez vojvođanskih Mađara"), 
            (u"Nevena Adžemović", u"Nova Srbija"), 
            (u"Sava Čojčić", u"Srpska napredna stranka"), 
            (u"Živko Ćurčić", u"Treća Srbija"), 
            (u"Miroslav Krišan", u"Demokratska stranka"), 
            (u"Milorad Soldatović", u"Vanstranačka ličnost"), 
            (u"Miodrag Stevanić", u"Srpska napredna stranka"), 
            (u"Miroslav Vasin", u"Demokratska stranka"), 
            (u"Nenad Grbić", u"Socijaldemokratska partija Srbije"), 
            (u"Vladimir Zaharijev", u"Demokratska stranka Srbije"), 
            (u"Ivan Bošnjak", u"Srpska napredna stranka"), 
            (u"Zoran Dragišić", u"Pokret radnika i seljaka"), 
            (u"Ilija Vojinović", u"Vanstranačka ličnost"), 
            (u"Đorđe Radinović", u"Srpska napredna stranka"), 
            (u"Siniša Lazić", u"Demokratska stranka"), 
            (u"Svetlana Đajić", u"Srpska radikalna stranka"), 
            (u"Dušan Jovanović", u"Demokratska stranka"), 
            (u"Borislav Rajkov", u"Srpska napredna stranka"), 
            (u"Edita Divković", u"Demokratska stranka"), 
            (u"Bojan Đurić", u"Liberalno demokratska partija"), 
            (u"Modest Dulić", u"Demokratska stranka"), 
            (u"Aleksandar Farkaš", u"Srpska napredna stranka"), 
            (u"Vladimir Ilić", u"Socijalistička partija Srbije"), 
            (u"Karolj Damjanov", u"Vanstranačka ličnost"), 
            (u"Strahinja Šljukić", u"Demokratska stranka Srbije"), 
            (u"Izabela Šerić", u"Demokratska stranka"), 
            (u"Zoran Perišić", u"Srpska napredna stranka"), 
            (u"Suzana Dulić", u"Demokratska stranka"), 
            (u"Dejan Trifunović", u"Socijaldemokratska partija Srbije"), 
            (u"Rajko Bojčić", u"Liga socijaldemokrata Vojvodine"), 
            (u"Emir Hašimbegović", u"Sandžačka demokratska partija"), 
            (u"Dragan Vujić", u"Partija ujedinjenih penzionera Srbije"), 
            (u"Čedomir Janjić", u"Srpska napredna stranka"), 
            (u"Zoran Antić", u"Socijalistička partija Srbije"), 
            (u"Bratislav Jugović", u"Pokret socijalista"), 
            (u"Branko Stanimirov", u"Demokratska stranka"), 
            (u"Vukašin Vujičić", u"Demokratska stranka"), 
            (u"Živorad Smiljanić", u"Socijalistička partija Srbije"), 
            (u"Dragan Janjić", u"Ujedinjeni regioni Srbije"), 
            (u"Petar Novaković", u"Srpska napredna stranka"), 
            (u"Atila Čengeri", u"SocijalDemokratska stranka"), 
            (u"Miodrag Manić", u"Demokratska stranka"), 
            (u"Miroljub Stojčić", u"Socijalistička partija Srbije"), 
            (u"Zoran Babić", u"Srpska napredna stranka"), 
            (u"Slobodan Stupar", u"Vanstranačka ličnost"), 
            (u"Tibor Vaš", u"Liga socijaldemokrata Vojvodine"), 
            (u"Radomir Dabetić", u"Socijalistička partija Srbije"), 
            (u"Saša Paunović", u"Demokratska stranka"), 
            (u"Mirjana Đoković", u"Srpska napredna stranka"), 
            (u"Živojin Mitrović", u"Vanstranačka ličnost"), 
            (u"Nebojša Malenković", u"Demokratska stranka"), 
            (u"Danilo Golubović", u"Vanstranačka ličnost"), 
            (u"Dragan Kolarević", u"Vanstranačka ličnost"), 
            (u"Darko Karan", u"Nova Srbija"), 
            (u"Igor Mirović ", u"Srpska napredna stranka"), 
            (u"Jovan Biočanin", u"Socijalistička partija Srbije"), 
            (u"Dragoljub Simonović", u"Srpska napredna stranka"), 
            (u"Miloš Antanasijević", u"Partija ujedinjenih penzionera Srbije"), 
            (u"Balša Božović ", u"Demokratska stranka"), 
            (u"Velibor Vukašinović ", u"Vanstranačka ličnost"), 
            (u"Milan Mrkšić", u"Socijalistička partija Srbije"), 
            (u"Zoran Živković", u"Nova stranka"), 
            (u"Milan Pajević", u"Ujedinjeni regioni Srbije"), 
            (u"Dejan Pavićević", u"Demokratska stranka"), 
            (u"Radoš Ljušić ", u"Srpska napredna stranka"), 
            (u"Zoran Kostić", u"Socijalistička partija Srbije"), 
            (u"Suzana Paunović", u"Socijaldemokratska partija Srbije"), 
            (u"Dragica Jevtović", u"Vanstranačka ličnost"), 
            (u"Momčilo Babić", u"Srpska napredna stranka"), 
            (u"Bratislav Gašić", u"Srpska napredna stranka"), 
            (u"Milan Lazović", u"Srpska napredna stranka"), 
            (u"Ostoja Mijailović", u"Srpska napredna stranka"), 
            (u"Zoran Todosijević", u"Nova Srbija"), 
            (u"Milorad Grčić", u"Srpska napredna stranka"), 
            (u"Marko Selaković", u"Vanstranačka ličnost"), 
            (u"Vesna Marjanović", u"Demokratska stranka"), 
            (u"Goran Đorđević", u"Srpska napredna stranka"), 
            (u"Nebojša Rodić", u"Srpska napredna stranka"), 
            (u"Lazar Krstić", u"Vanstranačka ličnost"), 
            (u"Nenad Borovčanin", u"Socijalistička partija Srbije"), 
            (u"Goran Perčević", u"Vanstranačka ličnost"), 
            (u"Velimir Ognjenović ", u"Srpska napredna stranka"), 
            (u"Goran Višnjić", u"Srpska napredna stranka"), 
            (u"Dmitar Đurović", u"Srpska napredna stranka"), 
            (u"Marko Atlagić", u"Srpska napredna stranka"), 
            (u"Nebojša Čović", u"Vanstranačka ličnost"), 
            (u"Ivan Tasovac", u"Vanstranačka ličnost"), 
            (u"Saša Radulović", u"Pokret 'Dosta je bilo'"), 
            (u"Vanja Udovičić", u"Vanstranačka ličnost"), 
            (u"Aleksandar Šapić", u"Vanstranačka ličnost"), 
            (u"Dragan Glamočić", u"Vanstranačka ličnost"), 
            (u"Tomislav Jovanović", u"Vanstranačka ličnost"), 
            (u"Aleksandar Bijelić", u"Demokratska stranka"), 
            (u"Vanja Vukić ", u"Socijalistička partija Srbije"), 
            (u"Ivica Tončev", u"Socijalistička partija Srbije"), 
            (u"Srđan Dragojević", u"Socijalistička partija Srbije"), 
            (u"Alfred Guzenbauer", u"Vanstranačka ličnost"), 
            (u"Stojan Nikolić", u"Demokratska stranka"), 
            (u"Gordana Predić", u"Socijaldemokratska partija Srbije"), 
            (u"Miodrag Poledica", u"Vanstranačka ličnost"), 
            (u"Vojin Nestorović", u"Vanstranačka ličnost"), 
            (u"Dominik Štros Kan", u"Vanstranačka ličnost"), 
            (u"Tatjana Babić", u"Vanstranačka ličnost"), 
            (u"Saša Mirković", u"Vanstranačka ličnost"), 
            (u"Stevan Krstić", u"Vanstranačka ličnost"), 
            (u"Jadranka Joksimović", u"Srpska napredna stranka"), 
            (u"Ivan Simič", u"Vanstranačka ličnost"), 
            (u"Oliver Antić", u"Srpska napredna stranka"), 
            (u"Radomir Nikolić", u"Srpska napredna stranka"), 
            (u"Dejan Ristić", u"Vanstranačka ličnost"), 
            (u"Franko Fratini", u"Vanstranačka ličnost"), 
            (u"Aleksandar Jovičić", u"Srpska napredna stranka"), 
            (u"Aleksandar Đorđević", u"Vanstranačka ličnost"), 
            (u"Miodrag Stojković", u"Demokratska stranka"), 
            (u"Nikola Mirkov", u"Vanstranačka ličnost"), 
            (u"Ljubivoje Slavković", u"Srpska napredna stranka"), 
            (u"Boris Ivković", u"Ujedinjeni regioni Srbije"), 
            (u"Boris Milićević", u"Socijalistička partija Srbije"), 
            (u"Siniša Kovačević", u"Srpski otadžbinski front"), 
            (u"Goran Vesić", u"Vanstranačka ličnost"), 
            (u"Vladimir Todorić", u"Demokratska stranka"), 
            (u"Stanislava Pak Stanković", u"Srpska napredna stranka"), 
            (u"Nikola Nikodijević", u"Socijalistička partija Srbije"), 
            (u"Tatjana Pašić", u"Demokratska stranka"), 
            (u"Siniša Mali", u"nestranačka ličnost"), 
            (u"Aleksandar Dačić", u"Socijalistička partija Srbije"), 
            (u"Vladimir Jelić ", u"Srpski pokret obnove"), 
            (u"Radovan Radović Raka", u"Srpska napredna stranka"), 
            (u"Aleksandar Jugović", u"Srpski pokret obnove"), 
            (u"Dragan Vukanić ", u"Srpska napredna stranka"), 
            (u"Ranka Savić", u"Vanstranačka ličnost"), 
            (u"Konstantin Arsenović", u"Partija ujedinjenih penzionera Srbije"), 
            (u"Vesna Kopitović", u"Demokratska stranka"), 
            (u"Vladimir Stamenković", u"Vanstranačka ličnost"), 
            (u"Predrag Milošević", u"Srpska napredna stranka"), 
            (u"Dejan Backović ", u"Socijalistička partija Srbije"), 
            (u"Krstimir Pantić ", u"Srpska napredna stranka"), 
            (u"Miodrag Rakić", u"SocijalDemokratska stranka"), 
            (u"Veroljub Arsić", u"Srpska napredna stranka"), 
            (u"Boris Ranković", u"SocijalDemokratska stranka"), 
            (u"Tatjana Matić", u"Socijaldemokratska partija Srbije"), 
            (u"Slobodan Lalović", u"Demokratska stranka Srbije"), 
            (u"Aleksandar Protić", u"Treća Srbija"), 
            (u"Dušan Nikezić", u"Demokratska stranka"), 
            (u"Nataša Vučković", u"Demokratska stranka"), 
            (u"Riza Halimi", u"Partija za demokratsko delovanje"), 
            (u"Kori Udovički ", u"Vanstranačka ličnost"), 
            (u"Tinde Kovač Cerović", u"SocijalDemokratska stranka"), 
            (u"Srđan Verbić", u"Vanstranačka ličnost"), 
            (u"Zlatibor Lončar", u"Srpska napredna stranka"), 
            (u"Dušan Vujović", u"Vanstranačka ličnost"), 
            (u"Snežana Bogosavljević Bošković", u"Socijalistička partija Srbije"), 
            (u"Dragi Nestorović", u"Srpska napredna stranka"), 
            (u"Milijan Stojanić", u"Srpska napredna stranka"), 
            (u"Marko Đurić", u"Srpska napredna stranka"), 
            (u"Dragan Jovanović", u"Srpska napredna stranka"), 
            (u"Marko Blagojević", u"Vanstranačka ličnost"), 
            (u"Milenko Dželetović", u"Srpska napredna stranka"), 
            (u"Milorad Mirčić", u"Srpska radikalna stranka"), 
            (u"Gordana Čomić", u"Demokratska stranka"), 
            (u"Željko Sertić", u"Srpska napredna stranka"), 
            (u"Ivan Simič", u"nestranačka ličnost"), 
            (u"Rifat Ličina ", u"Demokratska stranka"), 
            (u"Sanda Rašković-Ivić", u"Demokratska stranka Srbije"), 
            (u"Stojan Tintor", u"Srpska radikalna stranka"), 
            (u"Igor Bečić", u"Srpska napredna stranka"), 
            (u"Stevan Bjelić", u"Vanstranačka ličnost"), 
            (u"Mitropolit Amfilohije Radović", u"Vanstranačka ličnost"), 
            (u"Željko Nikač", u"Vanstranačka ličnost"), 
            (u"Episkop Filaret Mićević", u"Vanstranačka ličnost"), 
            (u"Goran Takić", u"Vanstranačka ličnost"), 
            (u"Aleksandar Vesić", u"Vanstranačka ličnost"), 
            (u"Bojan Đurić", u"Vanstranačka ličnost"), 
            (u"Branimir Kuzmanović", u"Demokratska stranka"), 
            (u"Stana Božović", u"Srpska napredna stranka"), 
            (u"Vladimir Đukanović", u"Srpska napredna stranka"), 
            (u"Dragomir Petronijević", u"Srpska napredna stranka"), 
            (u"Ministarstvo finansija", u"Vanstranačka ličnost"), 
            (u"Aleksandar Obradović ", u"Srpska napredna stranka"), 
            (u"Ministarstvo poljoprivrede", u"Vanstranačka ličnost"), 
            (u"Branislav Bugarski", u"Demokratska stranka"), 
            (u"Branislav Bogaroški", u"Liga socijaldemokrata Vojvodine"), 
            (u"Vesna Jovanović", u"Vanstranačka ličnost"), 
            (u"Slobodan Puzović", u"Demokratska stranka"), 
            (u"Marinika Tepić", u"Liga socijaldemokrata Vojvodine"), 
            (u"Nenad Stanković", u"Vanstranačka ličnost"), 
            (u"Slaviša Grujić", u"Liga socijaldemokrata Vojvodine"), 
            (u"Vladimir Pavlov", u"Vanstranačka ličnost"), 
            (u"Zoran Radoman", u"Demokratska stranka"), 
            (u"Saša Pavlov", u"Srpska napredna stranka"), 
            (u"Saša Levnajić", u"Srpska napredna stranka"), 
            (u"Ministarstvo pravde", u"Vanstranačka ličnost"), 
            (u"Aleksandar Đedovac", u"Srpska napredna stranka"), 
            (u"Bojan Radman", u"Socijalistička partija Srbije"), 
            (u"Mita Lačanski ", u"Srpska napredna stranka"), 
            (u"Vuk Radojević", u"Srpska napredna stranka"), 
            (u"Nenad Tomašević", u"Srpski pokret obnove"), 
            (u"Eržebet Kinka", u"Savez vojvođanskih Mađara"), 
            (u"Milan Bodiroža", u"Socijalistička partija Srbije"), 
            (u"Aleksandar Kovačević", u"Socijalistička partija Srbije"), 
            (u"Petar Filipović", u"Demokratska stranka"), 
            (u"Jelena Crnogorac", u"Jedinstvena Srbija"), 
            (u"Ferenc Borbelj", u"Savez vojvođanskih Mađara"), 
            (u"Rudolf Cegledi", u"Savez vojvođanskih Mađara"), 
            (u"Aniko Širkova", u"Demokratska stranka"), 
            (u"Miodrag Bakić", u"Socijalistička partija Srbije"), 
            (u"Srpska napredna stranka (SNS)", u"Vanstranačka ličnost"), 
            (u"Goran Orlić", u"Demokratska stranka"), 
            (u"Slađan Mančić", u"Srpska napredna stranka"), 
            (u"Marija Stojčević", u"Srpska napredna stranka"), 
            (u"Aleksandra Majkić", u"Srpska napredna stranka"), 
            (u"Pavle Markov", u"Srpska napredna stranka"), 
            (u"Svetislav Vukmirica", u"Srpska napredna stranka"), 
            (u"Eleonora Marjanović ", u"Socijalistička partija Srbije"), 
            (u"Borislav Staničkov ", u"Socijalistička partija Srbije"), 
            (u"Dragan Trifunović", u"Srpska napredna stranka"), 
            (u"Snežana Mrkaić", u"Socijalistička partija Srbije"), 
            (u"Velibor Milojičić", u"Srpska napredna stranka"), 
            (u"Ilija Maravić", u"Srpska napredna stranka"), 
            (u"Jene Maglai", u"Savez vojvođanskih Mađara"), 
            (u"Tomislav Veljković", u"Socijalistička partija Srbije"), 
            (u"Mihalj Kertes", u"Srpska napredna stranka"), 
            (u"Đuro Žiga", u"Srpska napredna stranka"), 
            (u"Nikola Ember ", u"Socijalistička partija Srbije"), 
            (u"Milan Kovačević", u"Srpska napredna stranka"), 
            (u"Tomislav Janković", u"Srpska napredna stranka"), 
            (u"Vladan Stajić", u"Srpska napredna stranka"), 
            (u"Saša Todorović", u"Srpska napredna stranka"), 
            (u"Vladislav Živanović", u"Srpski pokret obnove"), 
            (u"Bratislav Kažić", u"Srpska napredna stranka"), 
            (u"Milan Glušac", u"Srpska napredna stranka"), 
            (u"Goran Peković", u"Vanstranačka ličnost"), 
            (u"Marjana Maraš", u"Socijalistička partija Srbije"), 
            (u"Branislava Belić ", u"Socijalistička partija Srbije"), 
            (u"Ana Tomanova Makanova", u"Demokratska stranka"), 
            (u"Dušan Jakovljev", u"Liga socijaldemokrata Vojvodine"), 
            (u"Milan Ćuk", u"Srpska radikalna stranka"), 
            (u"Đorđe Milićević", u"Srpska napredna stranka"), 
            (u"Tamaš Tot", u"Demokratska stranka"), 
            (u"Petar Andrejić", u"Demokratska stranka"), 
            (u"Milivoj Vrebalov", u"Demokratska stranka"), 
            (u"Jelena Balašević", u"Demokratska stranka"), 
            (u"Predrag Berić", u"Demokratska stranka"), 
            (u"Ištvan Biro ", u"Demokratska stranka"), 
            (u"Pavle Budakov", u"Socijalistička partija Srbije"), 
            (u"Miroslav Španović", u"Partija ujedinjenih penzionera Srbije"), 
            (u"Predrag Amižić", u"Socijalistička partija Srbije"), 
            (u"Gavra Avramov", u"Socijaldemokratska partija Srbije"), 
            (u"Milenko Babić", u"Socijalistička partija Srbije"), 
            (u"Vesna Bjelić Francuski", u"Socijalistička partija Srbije"), 
            (u"Predrag Matejin", u"Srpska napredna stranka"), 
            (u"Bore Kutić", u"Srpska napredna stranka"), 
            (u"Darko Bađok", u"Srpska napredna stranka"), 
            (u"Vladimir Galić", u"Srpska napredna stranka"), 
            (u"Ministarstvo unutrašnjih poslova", u"Vanstranačka ličnost"), 
            (u"Maja Sedlarević", u"Liga socijaldemokrata Vojvodine"), 
            (u"Saša Homanov", u"Liga socijaldemokrata Vojvodine"), 
            (u"Radoica Milosavljević", u"Socijalistička partija Srbije"), 
            (u"Vidosav Radomirović", u"Vanstranačka ličnost"), 
            (u"Bratimir Vasiljević", u"Srpska napredna stranka"), 
            (u"Branko Radun", u"Vanstranačka ličnost"), 
            (u"Dragan Karadžić", u"Vanstranačka ličnost"), 
            (u"Zorica Šujica", u"Vanstranačka ličnost"), 
            (u"Simona Mitrović Dunjić", u"Vanstranačka ličnost"), 
            (u"Miomir Ilić", u"Socijalistička partija Srbije"), 
            (u"Ratko Stevanović ", u"Jedinstvena Srbija"), 
            (u"Tomislav Ilić", u"Srpska napredna stranka"), 
            (u"Vidoje Petrović  Vanstranačka ličnost"), 
            (u"Vidoje Petrović", u"Srpska napredna stranka"), 
            (u"Nebojša Zelenović", u"Zajedno za Srbiju"), 
            (u"Jasna Avramović", u"Srpska napredna stranka"), 
            (u"Miroslav Nikolić", u"Vanstranačka ličnost"), 
            (u"Ljiljana Đurđevac", u"Vanstranačka ličnost"), 
            (u"Robert Kolar", u"Liga socijaldemokrata Vojvodine"), 
            (u"Milenko Jovanov", u"Srpska napredna stranka"), 
            (u"Dejan Keresteš", u"Liga socijaldemokrata Vojvodine"), 
            (u"Predrag Ginculj", u"Srpska napredna stranka"), 
            (u"Dušan Inđić", u"Srpska napredna stranka"), 
            (u"Đorđe Vozarević", u"Vanstranačka ličnost"), 
            (u"Đorđe Čabarkapa", u"Socijalistička partija Srbije"), 
            (u"Nataša  Lalić", u"Liga socijaldemokrata Vojvodine"), 
            (u"Ilona Pelt ", u"Savez vojvođanskih Mađara"), 
            (u"Sabolč Kavai", u"Savez vojvođanskih Mađara"), 
            (u"Tinde Kovač", u"Savez vojvođanskih Mađara"), 
            (u"Lajoš Paći", u"Savez vojvođanskih Mađara"), 
            (u"Akoš Ujhelji", u"Savez vojvođanskih Mađara"), 
            (u"Ivana Zečević", u"Srpska radikalna stranka"), 
            (u"Lazar Čavić", u"Srpska radikalna stranka"), 
            (u"Nikola Lalić", u"Srpska radikalna stranka"), 
            (u"Branislav Blažić", u"Srpska napredna stranka"), 
            (u"Sreten Jovanović", u"Socijalistička partija Srbije"), 
            (u"Putevi Srbije", u"Vanstranačka ličnost"), 
            (u"Goran Radić", u"Socijalistička partija Srbije"), 
            (u"Tamara Zagorac Mešter", u"Socijalistička partija Srbije"), 
            (u"Livija Gavrilović", u"Socijalistička partija Srbije"), 
            (u"Marko Rovčanin", u"Socijalistička partija Srbije"), 
            (u"Slobodan Cvetković", u"Socijalistička partija Srbije"), 
            (u"Svetlana Vujović", u"SocijalDemokratska stranka"), 
            (u"Uranija Kozmidis", u"SocijalDemokratska stranka"), 
            (u"Jovan Ratković", u"SocijalDemokratska stranka"), 
            (u"Dejan Čapo", u"Liga socijaldemokrata Vojvodine"), 
            (u"Olena Papuga", u"Liga socijaldemokrata Vojvodine"), 
            (u"Arpad Fremond", u"Savez vojvođanskih Mađara"), 
            (u"Laslo Čikoš", u"Savez vojvođanskih Mađara"), 
            (u"Lukrecija Đeri", u"Savez vojvođanskih Mađara"), 
            (u"Grad Kragujevac", u"Vanstranačka ličnost"), 
            (u"Imre Kern ", u"Savez vojvođanskih Mađara"), 
            (u"Dušan Mijić", u"Vanstranačka ličnost"), 
            (u"Predrag Patić ", u"Liberalno demokratska partija"), 
            (u"Predrag Patić ", u"Liberalno demokratska partija"), 
            (u"Judita Popović", u"Liberalno demokratska partija"), 
            (u"Ružica Igić", u"Demokratska stranka Srbije"), 
            (u"Branislav Ristivojević", u"Demokratska stranka Srbije"), 
            (u"Zoran Sandić", u"Demokratska stranka Srbije"), 
            (u"Lazar Đurović", u"Demokratska stranka Srbije"), 
            (u"Zoran Đorđević", u"Srpska napredna stranka"), 
            (u"Slobodan Orlić", u"Socijaldemokratska partija Srbije"), 
            (u"Milorad Mijatović", u"Socijaldemokratska partija Srbije"), 
            (u"Tijana Blagojević", u"Demokratska stranka"), 
            (u"Đorđe Belamarić", u"Demokratska stranka"), 
            (u"Aleksandar Ivanović", u"SocijalDemokratska stranka"), 
            (u"Dušan Dinčić", u"Demokratska stranka"), 
            (u"Dejan Kovačević ", u"Demokratska stranka"), 
            (u"Dejan Stefanović", u"Socijalistička partija Srbije"), 
            (u"Stojan Nikolić", u"Demokratska stranka"), 
            (u"Ljubiša Đurović", u"Socijalistička partija Srbije"), 
            (u"Aca Jevtić", u"Liberalno demokratska partija"), 
            (u"Srđan Kolarić", u"Srpska napredna stranka"), 
            (u"Nikola Ristić", u"Vanstranačka ličnost"), 
            (u"Snežana Spasojević", u"Liberalno demokratska partija"), 
            (u"Edip Šerifov", u"Demokratska stranka"), 
            (u"Zoran Vuletić", u"Liberalno demokratska partija")
        ]

        return array_of_entities
